### PR TITLE
Compile with a slightly newer ZXing as well

### PR DESCRIPTION
**Pull request by vkrause**
This should not break compatibility with older versions. The C++14 bump is
needed as ZXing now has lambdas with auto parameters in its headers.

### CODE REVIEW

**Comment by tanius** [comment]
Confirmed to not break older versions, as it still works with ZXing-C++ 1.0.8 (which currently the minimum version this software depends on). Good to merge! Thank you for providing the very first pull request for this fledgling software :blush:

Seeing that you're an experienced KDE developer: if you have any words of wisdom for the future direction of this application, I'd appreciate it a lot. It's really my first Kirigami / KDE application and I might be missing obvious things around integrating with KDE. Feel free to open an issue if you have input for me.

**Comment by vkrause** [comment]
I haven't looked deeper into the code yet, what I did notice though is this also does camera-based barcode scanning, code which is duplicated countless times by now, so that's something for us to look into providing as part of a library eventually.

For exploring this further I'm currently stuck on creating the database. Last night's commit did add the missing frc script, but now I'm running into a runtime error there:
```
NameError: undefined local variable or method `args' for main:Object
  /k/src/foodrescue-content/scripts/frc:129:in `<top (required)>'
```

Btw, we have our yearly KDE conference starting tomorrow (https://akademy.kde.org/2020). That goes on for an entire week (and is all online this time for obvious reasons). That might be a good opportunity to meet e.g. the Kirigami team and exchange feedback in both directions, and to explore possible ways of collaboration :)

**Comment by tanius** [comment]
> For exploring this further I'm currently stuck on creating the database.

Yes, I urgently need to complete and document the database build process. For now, the simplest solution is to [download the Android APK](http://fairdirect.org/downloads/foodrescue.apk), unzip it and copy the SQLite3 database file contained there to `/usr/local/share/foodrescue/foodrescue-content.sqlite3`. The Food Rescue application will find it there when you start it.

Thank you for the pointer towards the KDE conference. I'll certainly visit there and see who I can meet!
